### ISSUE TITLE
frontend の proto 関連のファイルの置き場所

### ISSUE THREAD

**Issue by K-shir0** [ictsc/ictsc-outlands#226]
## 内容　

* turborepo を使って packages 以下に配置するのがよさそう

**Comment by logica0419** [comment]
設定ファイルを書いたので、これの各プラグインの「out」を書き換えれば書き出し先が変わります
https://github.com/ictsc/ictsc-outlands/pull/225/commits/e733f21948d6c7338a34ba8dd83de21783d773f4

**Comment by logica0419** [comment]
https://connectrpc.com/docs/web/getting-started/
https://connectrpc.com/docs/web/generating-code/
https://buf.build/docs/reference/cli/buf/generate

この辺参考にコマンド書いて、今`frontend/proto`に正常に書き出されるまではやったので、もし何かわからないことあったr聞いてください
ちょっとドキュメント書く時間はなさそうなので、コマンドから雰囲気読み取ってくれると嬉しいです

**Comment by K-shir0** [comment]
@logica0419 承知です！バックエンド最優先だと思うので資料見ながらそこら辺はよしなにやってみます。なにか続報あればログをここに流そうと思います。

**Comment by logica0419** [comment]
よろしくお願いします…
